
server:
  port: 8445

spring:
  profiles:
    active: test

  session:
    store-type: none

  servlet:
    multipart:
      max-file-size: 40MB

  jackson:
    default-property-inclusion: non_null

  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 7200000
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        jdbc.batch_size: 5
        default_batch_fetch_size: 500

logging:
  level:
    org:
      hibernate:
        type: error

---

spring:
  profiles: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

---

spring:
  profiles: dev

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/DB_EMOTION
    username: emotion
    password: 2m0t!0n

logging:
  level:
    org:
      hibernate:
        type: debug